#!/usr/bin/env bash
# display Best School 10 times and replace the ninth line with Hi

COUNTER = 0
while [ $COUNTER -lt 11 ]
do 
 if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let COUNTER+=1
done
